# frozen_string_literal: true

module Gemnesis
  # Parses `gemnesis.rb` user config → validated struct → C header for SGDK.
  #
  # Trust model: `gemnesis.rb` is executed as Ruby (instance_eval). It lives
  # inside the user's own project and is no more dangerous than the Makefile
  # or `Rakefile` next to it. Documented in README.
  class Config
    REGIONS = { ntsc: "NTSC", pal: "PAL", both: "NTSC/PAL" }.freeze
    MAX_TITLE_LEN = 48

    attr_accessor :title, :region, :author

    def self.load_file(path)
      raise Gemnesis::Error, "no gemnesis.rb at #{path}" unless File.exist?(path)

      Gemnesis.send(:reset_pending_config!)
      begin
        Kernel.load(path)
      rescue StandardError, ScriptError => e
        raise Gemnesis::Error, "gemnesis.rb: #{e.message}"
      end

      cfg = Gemnesis.send(:take_pending_config!)
      raise Gemnesis::Error, "gemnesis.rb missing `Gemnesis.configure { |g| ... }` block" if cfg.nil?

      cfg.validate!
      cfg
    end

    def validate!
      validate_title!
      validate_region!
      raise Gemnesis::Error, "author required in gemnesis.rb" if author.to_s.strip.empty?
    end

    def to_header
      <<~HEADER
        /* auto-generated by gemnesis — do not edit. Regenerate via `gemnesis build`. */
        #ifndef GEMNESIS_CONFIG_H
        #define GEMNESIS_CONFIG_H

        #define GAME_TITLE  "#{escape(title)}"
        #define GAME_REGION "#{REGIONS.fetch(region)}"
        #define GAME_AUTHOR "#{escape(author)}"

        #endif
      HEADER
    end

    private

    def validate_title!
      t = title.to_s
      raise Gemnesis::Error, "title required in gemnesis.rb" if t.strip.empty?
      raise Gemnesis::Error, "title too long: #{t.length} chars (max #{MAX_TITLE_LEN})" if t.length > MAX_TITLE_LEN
      raise Gemnesis::Error, "title must be ASCII (got #{t.inspect})" unless t.ascii_only?
    end

    def validate_region!
      return if REGIONS.key?(region)

      raise Gemnesis::Error,
            "region invalid: #{region.inspect} (expected one of #{REGIONS.keys.inspect})"
    end

    def escape(str)
      str.to_s.gsub("\\", "\\\\").gsub('"', '\\"')
    end
  end

  class << self
    def configure
      cfg = Config.new
      yield cfg
      @pending_config = cfg
    end

    private

    def reset_pending_config!
      @pending_config = nil
    end

    def take_pending_config!
      cfg = @pending_config
      @pending_config = nil
      cfg
    end
  end
end
