# frozen_string_literal: true

module Gemnesis
  # Generates `src/boot/rom_head.c` from a validated Config. The Mega Drive
  # ROM header is a fixed 256-byte struct at offset 0x100. SGDK exposes it
  # as `ROMHeader rom_header` — we ship our own to replace SGDK's default
  # "SAMPLE PROGRAM" with the user's title/author/region.
  #
  # SGDK's makefile.gen uses an order-only prereq for src/boot/rom_head.c,
  # so a pre-existing file is left alone.
  class RomHeader
    DEFAULT_COPYRIGHT_PREFIX = "(C)"

    REGION_CODES = {
      ntsc: "U               ",
      pal: "E               ",
      both: "JUE             "
    }.freeze

    def initialize(config)
      @config = config
    end

    def to_c
      <<~CODE
        /* auto-generated by gemnesis — regenerate via `gemnesis build`. */
        #include "genesis.h"

        __attribute__((externally_visible))
        const ROMHeader rom_header = {
        #if (ENABLE_BANK_SWITCH != 0)
            "SEGA SSF        ",
        #elif (MODULE_MEGAWIFI != 0)
            "SEGA MEGAWIFI   ",
        #else
            "SEGA MEGA DRIVE ",
        #endif
            "#{copyright}",
            "#{padded_title}",
            "#{padded_title}",
            "GM 00000000-00",
            0x000,
            "JD              ",
            0x00000000,
        #if (ENABLE_BANK_SWITCH != 0)
            0x003FFFFF,
        #else
            0x000FFFFF,
        #endif
            0xE0FF0000,
            0xE0FFFFFF,
            "RA",
            0xF820,
            0x00200000,
            0x0020FFFF,
            "            ",
            "#{padded_notes}",
            "#{region_code}"
        };
      CODE
    end

    private

    def padded_title
      escape(pad(@config.title.to_s, 48))
    end

    def copyright
      author = @config.author.to_s
      escape(pad("#{DEFAULT_COPYRIGHT_PREFIX}#{author}", 16))
    end

    def padded_notes
      escape(pad("Built with gemnesis", 40))
    end

    def region_code
      REGION_CODES.fetch(@config.region)
    end

    def pad(str, width)
      str.slice(0, width).ljust(width)
    end

    def escape(str)
      str.gsub("\\", "\\\\").gsub('"', '\\"')
    end
  end
end
